Testing
Iqbal-Elham/Math-Magician pull request #6
Opened 2023-03-01 20:51 UTC by Iqbal-Elham

## Math magicians: Tests
This is the Fifth project of the Math Magicians application. We Add tests for the component and logic JS file. The requirements of this project are:

- Using linters to free of errors.
- Using Gitflow
- Documented in professional way
- Write unit tests for the files `operate.js` and `calculate.js` using Jest.
- Use Jest snapshots to test the components.

2023-03-01 23:31 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @Iqbal-Elham and @fithamlak 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow Gitflow :heavy_check_mark: 
- Use of pair-programming-o :heavy_check_mark: 


## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-01 23:31 UTC, tresorsawasawa commented on src/components/__test__/CalculatorPage.test.js
> +});
- [ ] As required for the project, kindly ensure that there are the usage of React Testing Library to simulate user interaction.

2023-03-01 23:31 UTC, tresorsawasawa commented on src/logic/calculate.test.js
> +});
- [ ] As required for the project, all the functionalities & scenarios of the `operate.js` and` calculate.js` modules  are covered with tests using Jest. Kindly ensure that you also add tests on the `+/-`, ...

2023-03-01 23:31 UTC, tresorsawasawa commented on README.md
- [ ] Kindly ensure that you also fill the `Acknowledgments` and `Show your support` sections from your your README with correct and meaningful content

2023-03-02 11:46 UTC, rotimiazeez approved these changes
Hi Team 👏🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good job working on the suggested changes 😉
- Tests are passing ✔️
- No linter error 👍🏽 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-02 11:51 UTC, merged